<?php

namespace App\Modules\Email\Support;

use Illuminate\Contracts\Cache\Lock;
use Illuminate\Queue\Middleware\WithoutOverlapping;
use Illuminate\Support\Facades\Cache;

final class EmailAccountProviderLock
{
    public const RELEASE_AFTER_SECONDS = 15;

    public const EXPIRY_BUFFER_SECONDS = 60;

    public const CACHE_PREFIX = 'laravel-queue-overlap:';

    /**
     * Keep the established key stable across account fetch, targeted Drafts
     * refresh, and later controlled import jobs. The shared key serializes
     * provider reads/writes without conflating different accounts.
     */
    public static function middleware(int $accountId, int $jobTimeout): WithoutOverlapping
    {
        return (new WithoutOverlapping(self::key($accountId)))
            ->shared()
            ->releaseAfter(self::RELEASE_AFTER_SECONDS)
            ->expireAfter(max(1, $jobTimeout) + self::EXPIRY_BUFFER_SECONDS);
    }

    public static function key(int $accountId): string
    {
        return 'email-fetch-account:'.$accountId;
    }

    /**
     * Synchronous provider actions use the exact cache key generated by the
     * shared queue middleware. A null result means another account provider
     * operation owns the lease; callers must fail closed before provider I/O.
     */
    public static function acquire(int $accountId, int $seconds = 360): ?Lock
    {
        $lock = Cache::lock(self::cacheKey($accountId), max(1, $seconds));

        return $lock->get() ? $lock : null;
    }

    public static function cacheKey(int $accountId): string
    {
        return self::CACHE_PREFIX.self::key($accountId);
    }
}
